#!usr/bin/ python3
'''
@author: alec
@name: airduka extended platform
@year: 2023
'''
from datetime import datetime
from typing import Optional

from pydantic import BaseModel,Field
from fastapi import Body

date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

class BaseInventory(BaseModel):
    product_reference_number: str = Field(default=None,title="Product Reference Number",description="A unique ID generated by the system that identifies a Product listed on AirDuka shop")
    product_qty: Optional[int] = Field(default=1,title="QTY",description="Number of a product")
    product_moq: Optional[int] = Field(default=1,title="MOQ",description="Minimum Order Quantity")
    company_reference_number: str = Field(default=None,title="Company Reference Number",description="A unique ID generated by the system that identifies a Vendor created on AirDuka shop")
    branch_gps_coordinates: str = Field(default=None,title="Merchant's Geo-location",description="Defines the location of a Merchant based on map's co-ordinates i.e. Latitude and Longitude")
    stock_expiry_date: Optional[datetime] = Field(default=date,title="Stock Expiry Date",description="")

class CreateInventory(BaseInventory):
    class Config:
        schema_extra = {
			"example":{
                            "error": False,
                            "data": {
                                    "product_reference_number": "XCEDFRGEWZ",
                                    "product_qty":1,
                                    "product_moq":1,
                                    "company_reference_number":"1234567890",
                                    "branch_gps_coordinates":"x,y",
                                    "stock_expiry_date": date
                                    },
                            "message": "The product has been added onto the inventory successfully"  
			            }
		}