
#!usr/bin/ python3
'''
@author: alec
@name: airduka extended platform
@year: 2023
'''
from typing import Optional
from pydantic import BaseModel, Field

class BaseProduct(BaseModel):
        product_title: str = Field(default=None, title="Title",description="A name that identifies a product")
        product_price: float = Field(default=None,title="Price",description="Amount paid of a product")
        product_description: str = Field(default=None,title="Description",description="Detailed description of a product")
        product_sku: str = Field(default=None,title="SKU",description="Stock Keeping Unit:-helps merchant internally track stock levels")
        product_qty: Optional[int] = Field(default=1,title="QTY",description="Number of a product")
        product_moq: Optional[int] = Field(default=1,title="MOQ",description="Minimum Order Quantity")
        company_reference_number: str = Field(default=None,title="Company Reference Number",description="A unique ID generated by the system that identifies a Vendor on AirDuka shop")
        image_url: Optional[str] | None = None
        video_url: Optional[str] | None = None

class CreateProduct(BaseProduct):
	class Config:
		schema_extra = {
			"example": {
                            "error": False,
                            "data": {
                                    "product_title":"Blue fountain Ink",
                                    "product_price":355.00,
                                    "product_description":"Just another awesome product stocked on AiDuka.",
				    "product_sku":"SKU-2345-MFHJK",
                                    "product_reference_number": "XCEDFRGEWZ",
                                    "product_qty":1,
                                    "product_moq":1,
                                    "company_reference_number":"1234567890",
                                    "image_url":"https://",
                                    "video_url":"https://"
                                    },
                            "message": "The product has been created successfully"  
			            }
		}

class CreateMultipleProduct(BaseModel):
	data: Optional[list[BaseProduct]] = None
	class Config:
                orm_mode = True
                schema_extra = {
                "example": {
                        "error": False,
                        "message": "The batch request has been queued successfully"}
                }
		

class CreateMultipleProductResponse(BaseModel):
	class Config:
                orm_mode = True
                schema_extra = {
                "example": {
                        "error": False,
                        "message": "The batch request has been queued successfully"}
                }
		
		
class ModifyProduct(BaseModel):
    data: Optional[BaseProduct]
    class Config:
        schema_extra = {
			"example": {
                            "error": False,
                            "data": {
                                    "product_title":"Blue fountain Ink",
                                    "product_price":355.00,
                                    "product_description":"Just another awesome product stocked on AiDuka.",
                                    "product_reference_number": "XCEDFRGEWZ",
                                    "product_qty":1,
                                    "product_moq":1,
                                    "company_reference_number":"1234567890",
                                    "image_url":"https://",
                                    "video_url":"https://"
                                    },
                            "message": "Product has been modified successfully"  
			            }
		}

class GetProduct(BaseModel):
	error: Optional[bool]
	data: Optional[CreateProduct]
	message: Optional[str]
    
	class Config:
		schema_extra = {
			"example": {
                            "error": False,
                            "data": {
                                    "product_title":"Blue fountain Ink",
                                    "product_price":355.00,
                                    "product_description":"Just another awesome product stocked on AiDuka.",
                                    "product_reference_number": "XCEDFRGEWZ",
                                    "product_qty":1,
                                    "product_moq":1,
                                    "company_reference_number":"1234567890",
                                    "image_url":"https://",
                                    "video_url":"https://"
                                    },
                            "message": "The product has been retrieved successfully"  
			            }
		}